### ISSUE TITLE
Auto-renewal of the auth token

### ISSUE THREAD

**Issue by docanaebi** [EGA-archive/ega-fuse-client#1]
At the moment there is a 1hour limit for mounting the EGA dataset, after that, you would need to stop the jvm and launch it again with the newly issued token.

Having a sort of auto-renewal feature would be very useful. Would it make sense to read the token from a file, rather than passing it as a parameter?

**Comment by AlexanderSenf** [comment]
A refresh token can now be specified along with the bearer token. In that case a config file with an AAI client ID and Secret must be specified, so that the FUSE layer can automatically make the REST call to refresh the bearer token.
