### ISSUE TITLE
change hard coded base_url to be more configurable or add as a CLI option

### ISSUE THREAD

**Issue by nanjiangshu** [EGA-archive/ega-fuse-client#2]
The variables `baseUrl` and `baseFile` are hard coded at 

https://github.com/EGA-archive/ega-fuse-client/blob/master/src/main/java/eu/elixir/ega/ebi/egafuse/EgaFuse.java#93
https://github.com/EGA-archive/ega-fuse-client/blob/master/src/main/java/eu/elixir/ega/ebi/egafuse/EgaFuse.java#95

It will be great that it can be set as a CLI option.

**Comment by AlexanderSenf** [comment]
Good point. I will add a CLI option for the base URL. The baseFile is not used; I cleaned up the code a bit here. This brings up a good point though: The FUSE could also still work when mounting a local file system - I will add that as a task.
