### ISSUE TITLE
Secret?

### ISSUE THREAD

**Issue by pneerincx** [EGA-archive/ega-fuse-client#22]
In a public repo this does not sound very "_secret_":

https://github.com/EGA-archive/ega-fuse-client/blob/3fad0df59f8e577b582e5a295fe2326014ea8dfe/src/main/resources/application.properties#L2

**Comment by jorizci** [comment]
@pneerincx indeed. Our current OpenID server does not allow us to have clients that will authenticate without the usage of secret, as such is not much of a secret. We have this on our roadmap and it will be removed in future versions. This secret, though is independent from each user credentials and can only be used to authenticate users.

**Comment by pneerincx** [comment]
@jorizci Ok, thanks for the info.
