### ISSUE TITLE
Running multiple instances leaks data sets from one instance to another.

### ISSUE THREAD

**Issue by pneerincx** [EGA-archive/ega-fuse-client#25]
We've tried to run two instances of the EGA Fuse client (version 2.1.0) for two different projects/groups that share the same HPC cluster. Both groups have their own mount point for the EGA Fuse client and have their own credential files with different user names and passwords. The instance that is started first is for a project that has access to 5 EGA data set accessions. These show up as expected in the mount point. The second instance should have access to 2 different EGA data set accessions. Those 2 show up in the mount point for the second instance but in addition to the 5 data sets that should only be accessible to the first instance. This is a major security issue...

**Comment by pneerincx** [comment]
Dear @jorizci I'm on CentOS 7.x servers and using a systemd unit file like this https://github.com/EGA-archive/ega-fuse-client/pull/24/files#diff-c7831977797d52650fcfa3bf118d7cf44731519ce9d1b73c400e98fa30ca1687
Together with a `*.env` file for environment variables and a `*.cf` credential file that contains account + password. Examples are in the same PR:
* https://github.com/EGA-archive/ega-fuse-client/pull/24/files#diff-f27208f35424b580c30d7151a9d88dbeab43034eaf34808573cde6cde63b7f70
* https://github.com/EGA-archive/ega-fuse-client/pull/24/files#diff-607b640b71de190f70b17d4b289fdd31e52be213c5a7305154619d781833ca0f

I'm currently using for the Cineca project:

* /etc/ega-fuse-client.d/cineca.env
  ```
   EGA_FUSE_CLIENT_MOUNTPOINT=/groups/umcg-cineca/prm08/ega-fuse-client
   EGA_FUSE_CLIENT_JAVA_HOME=/etc/alternatives/jre_11_openjdk
  ```
* /etc/ega-fuse-client.d/cineca.cf
  ```
   username:****johan****@umcg***
   password:****************
  ```
For the Solve-RD project:
* /etc/ega-fuse-client.d/solve_rd.env
  ```
   EGA_FUSE_CLIENT_MOUNTPOINT=/groups/umcg-solve-rd/prm08/ega-fuse-client
   EGA_FUSE_CLIENT_JAVA_HOME=/etc/alternatives/jre_11_openjdk
   ```
* /etc/ega-fuse-client.d/solve_rd.cf
  ```
   username:****helpdesk@umcg***
   password:****************
  ```
This services are enabled and started with
```
systemctl enable ega-fuse-client@solve_rd.service
systemctl start ega-fuse-client@solve_rd.service
systemctl enable ega-fuse-client@cineca.service
systemctl enable ega-fuse-client@cineca.service
```
For the record, this is currently on a test server only, so there is no issue yet with members of one project having access to data sets from the other project. On the test server I can see:
```
ls -1 /groups/umcg-solve-rd/prm08/ega-fuse-client/
EGAD00001005352
EGAD00001006605
EGAD00001006606
EGAD00001006607
EGAD00001006870

ls -1 /groups/umcg-cineca/prm08/ega-fuse-client/
EGAD00001000821
EGAD00001003971
EGAD00001005352
EGAD00001006605
EGAD00001006606
EGAD00001006607
EGAD00001006870
```
The latter is wrong as the cineca project should only have access to the first two data sets EGAD00001000821 and EGAD00001003971, but to the other 5.

**Comment by pneerincx** [comment]
I now also tried running the Fuse client for only one of the groups at a time. The instance for Solve-RD is Ok, but if I run the Fuse client only for Cineca I still see too many data sets. This makes me wonder if what I'm seeing is simply caused by misconfiguration of the account for Cineca having access to too many data sets as opposed to a bug in the EGA Fuse client code....

**Comment by jorizci** [comment]
Most likely, as I could not reproduce the bug. I'm currently on leave could
you pass the information of those accounts for further verification to
***@***.***? (I'm on leave currently)

**Comment by pneerincx** [comment]
Check, I will contact the usual suspects ;)

**Comment by pneerincx** [comment]
We have now confirmed this was an issue with an account and not a bug in code, so case closed.
